# Generated by Django 5.2.5 on 2025-11-05 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('compact_view', models.BooleanField(default=False)),
                ('refresh_interval', models.IntegerField(default=10, help_text='Dashboard refresh interval in seconds')),
                ('items_per_page', models.IntegerField(default=25, help_text='Number of items to display per page')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('email_anomalies', models.BooleanField(default=True)),
                ('email_critical', models.BooleanField(default=True)),
                ('email_reports', models.BooleanField(default=False)),
                ('email_updates', models.BooleanField(default=False)),
                ('browser_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
